spring:
  application:
    name: EduTrack-BackEnd
    
  # Disable Docker Compose integration
  docker:
    compose:
      enabled: false
      
  # Database Configuration - MariaDB
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3307/edutrack?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useGSSAPI=false}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: org.mariadb.jdbc.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        
# Security Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789mySecretKey123456789}
  expiration: 86400000

# CORS Configuration
cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,https://localhost:3000}

# Server Configuration
server:
  port: 8080

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logging Configuration
logging:
  level:
    com.edutrack: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
